TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devBergozBCM.db
DB_INSTALLS += $(TOP)/BergozBCMSup/devBergozBCM.proto

#=======================================
include $(TOP)/configure/RULES
